### ISSUE TITLE
Reloading page after highlighting HTML alters rendering of highlighted HTML

### ISSUE THREAD

**Issue by jkroes** [raindropio/app#104]
Using [nunjucks documentation](https://mozilla.github.io/nunjucks/templating.html#autoescaping) as an example.

Before highlighting:
![image](https://github.com/raindropio/app/assets/18478163/14600b78-a65b-465c-be16-5a49e233eccb)

After highlighting:
![image](https://github.com/raindropio/app/assets/18478163/30343fa5-e638-43bf-99cb-1e3040064ab5)

**Comment by taylankasap** [comment]
Any updates on this? Is there any way I can help to have this issue fixed?

**Comment by exentrich** [comment]
Fixed in all browsers, except Firefox, because it still not support [CSS Custom Highlights](https://developer.mozilla.org/en-US/docs/Web/API/CSS_Custom_Highlight_API)
