### ISSUE TITLE
Is there a way to add a link to Raindrop when I have added it to Instapaper?

### ISSUE THREAD

**Issue by halloleo** [raindropio/app#105]
I didn't find any discussion board (my bad if I overlooked it), so I post it here:

Can I tell Raindrop to add a link to Raindrop when I have added it to Instapaper? Pinboard (where I'm coming from) was for a long time able to do this, but it has stopped doing so without notice.

**Comment by exentrich** [comment]
Hello! Yes:
https://ifttt.com/connect/instapaper/raindrop
