### ISSUE TITLE
[Feature Request] [UX] [Save] Find to reveal sub-collections

### ISSUE THREAD

**Issue by gerardbosch** [raindropio/app#106]
Hi there! I describe the idea and the motivation:

* I'm using collections and nested collections to organize the pages I bookmark.
* When I want to bookmark a page, I use the collection picker to find the right collection.
* But most of the time I'm not aware of all sub-collections that I created under the "main collection", so I cannot save to the sub-collection that's best fitted for the page by directly using the search, I mean, without browsing the whole collections list.

Here is a trivial example of what I mean:

`programming` collection sub-tree:

![image](https://github.com/raindropio/app/assets/30733556/51c75e57-fc3f-42e8-8baa-633f37995c6f)

When I want to save a page under `programming` collection, I'd like that the _search function_ would also show all nested collections, so I can pick the most suited one, like the following **prototype**:

![image](https://github.com/raindropio/app/assets/30733556/eb0b7604-f5e0-4001-ba54-d7c3752c762d)

### Ideas

* Nested collections could have an arbitrary depth, so showing them **all** on main collection search could be messy. So nested collections could expand further after writing the path to them, e.g. `programming/Java` could show only collections immediately under `Java/`.
* In case the nested collection lookup produce messy output (too  many results), using a slash `/` to trigger the nested search maybe could help, but direct search seems easier from the user side at first sight.

I hope this helps to improve this awesome tool! 🎉

**Comment by exentrich** [comment]
Please add feature requests here https://better.raindrop.io/

**Comment by gerardbosch** [comment]
For the record, the feature request was already in better.raindrop.io, but I originally put the full description and screenshots here in this issue.

https://better.raindrop.io/feature-requests/p/save-ux-find-to-reveal-sub-collections

Thanks

**Comment by exentrich** [comment]
> @exentrich better.raindrop.io is down now. How can we file feature requests now?
> 
> Is it https://raindropio.canny.io/feature-requests?

Sorry the new domain is
https://raindropio.canny.io/
