### ISSUE TITLE
Favicons not showing when searching from URL bar using "rd" keyword

### ISSUE THREAD

**Issue by shashankshirke** [raindropio/app#108]
Favicons not showing when searching directly from the URL address bar.

In Chrome, when searching from the URL address bar using the "rd" keyword, favicons are not showing correctly as can be seen in the image below 👇

<img width="1497" alt="image" src="https://github.com/raindropio/app/assets/7890147/334a1ff2-806d-4f29-9a80-ff65dc48fd25">

Favicons are correctly showing in the list of bookmarks in Raindrop extension but when searching from the URL bar, the favicons are not shown and instead the default Raindrop cloud icon is shown for all bookmarks.

@exentrich please check this issue.

**Comment by exentrich** [comment]
Unfortunately this is how Chrome shows search results from browser extension.
Nothing can be done with it
