### ISSUE TITLE
[Question] Change search engine shortcut `rd`

### ISSUE THREAD

**Issue by gerardbosch** [raindropio/app#109]
_(Maybe this is not the right place for questions, and using Github Discussion would be more appropriate, but it is disabled in this repo)_

Hi there,

I'm using Brave browser.
Is is possible to customize the address bar search keyword? Instead of `rd` I'd prefer to use `r` for example.

Maybe this is a Feature Request more than a question..? 🙂

Thanks!

---

Docs: https://help.raindrop.io/browser-extension/#search-from-address-bar

### Screnshots
![image](https://github.com/raindropio/app/assets/30733556/7eab2e45-0134-41ff-85ed-819f3c26759e)

Other search engines:

![image](https://github.com/raindropio/app/assets/30733556/d952872c-d20f-4f84-a8f4-a421b0107794)

**Comment by exentrich** [comment]
Unfortunately it’s not possible to make it user configurable. Browsers just don’t have such API.
Originally we had `r` shortcut but many users complain about it, so I decided to change it to `rd`.

**Comment by gerardbosch** [comment]
I've got an idea. Would it be possible to add OpenSearch on app.raindrop.io site?

This way, a browser with this option enabled would add it as a search engine, and allow to configure it like the examples highlighted below. 

1. Enable external search engines detection:

![image](https://github.com/raindropio/app/assets/30733556/f1efabf6-82b4-4579-ba50-18a557c7bbeb)

2. After visiting app.raindrop.io, you should be able to activate it and configure the shortcut like in this examples:

![image](https://github.com/raindropio/app/assets/30733556/baab9591-ccf4-4fc3-b783-195a19fe6caf)

3. Once done, you can deactivate the search engine indexing if desired.

What do you think?
