### ISSUE TITLE
New bookmark shortcut stopped working in Firefox

### ISSUE THREAD

**Issue by brttbndr** [raindropio/app#111]
There seems to be a regression in the latest extension on Firefox.

### Repro Steps

1. Navigate to some site
2. Hit the assigned hotkey for "New bookmark / Save highlight"

Expected: Dialog opens with newly created bookmark
Get instead: Nothing visibly happens

In the Browser Console, this exception is logged:

```
TypeError: r is undefined [background.js:1:97852](moz-extension://86563863-3c55-4daf-8721-0045cb3b09ba/background.js)
```

### Source?

In the minified code, that puts us here:

```
async function or(t,r){switch(t){case"save_page":{const{url:t="",id:n}=r
```

which seems to be this recent commit:

https://github.com/raindropio/app/blame/c6e740c0e3f9e2ab278481d896279eba486d0a84/src/target/extension/background/commands.js#L14

**Comment by archetyped** [comment]
Experiencing this issue as well.  Would be great to get a fix.
Thanks.

**Comment by brttbndr** [comment]
My workaround for now is:

1. Go to list of previous versions at https://addons.mozilla.org/en-US/firefox/addon/raindropio/versions/
2. Click on Download file under "Older Versions - Version 6.6.13" (the most recent previous version)
3. Click "Add" when prompted to "Add Raindrop.io?"
4. Go to the list of extensions at "Settings and themes"
5. Click to view details for Raindrop.io and disable automatic updates

With version pinned at 6.6.13, the hotkey works as expected

**Comment by brttbndr** [comment]
Fixed by https://github.com/raindropio/app/commit/35e8d9f257060f147b8ed4639e39c2f1f467ce3b
