### ISSUE TITLE
[Feature Request] Add “Note” field to tags.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [raindropio/app#112]
It's already available in directories and bookmarks.

**https://github.com/nextcloud/tasks/issues/2395#issue-1991455758**

> I want to add a description to some tags to provide additional information, the same as I would a [bookmark].

**Comment by exentrich** [comment]
Please add feature requests here https://better.raindrop.io/

**Comment by RokeJulianLockhart** [comment]
> https://github.com/raindropio/app/issues/112#issuecomment-2061539722

@exentrich, transferred to https://better.raindrop.io/feature-requests/p/add-note-field-to-tags per https://github.com/raindropio/app/issues/112#issuecomment-2061528222.
