### ISSUE TITLE
Only a subset of bookmarks shown when clicking on tags

### ISSUE THREAD

**Issue by github-account1111** [raindropio/app#114]
I have 35 bookmarks for travel, and Raindrop seems to realize that:

![image](https://github.com/raindropio/app/assets/5728319/aa3318e4-0048-4f81-8772-39d8221d59e6)

However, when I click on the tag I'm only shown 28 bookmarks:

![image](https://github.com/raindropio/app/assets/5728319/11570f5c-24c2-482c-a8ce-cc59dac95405)

I know for a fact it's not showing everything.
This is the case for many of the tags.

**Comment by tgray** [comment]
Most of my tags aren't showing any results at all.   It seems like the search index or something might be broken.

**Comment by brezanac** [comment]
Same issue. Seven out of eight results for existing bookmarks simply refuse to appear in the search results.

**Comment by g180** [comment]
Hi guys, this issue is pretty much a duplicate of #113 and I believe it's being taken care.
We basically just have to wait for one more day or two.

FYI: https://nitter.net/xeraa/status/1736019592466637303

**Comment by exentrich** [comment]
Disaster happen with our search index. We hosted our search engine on https://github.com/elastic cloud. They just deleted our entire account.

Do not worry, all data is safe. I just need to rebuild search index on a different hosting provider. But this require few days to complete unfortunately

**Comment by exentrich** [comment]
70% is complete, most likely tomorrow search index migration will be done

**Comment by lilskippyy** [comment]
> 70% is complete, most likely tomorrow search index migration will be done

Thanks for letting us know!

**Comment by pencilcheck** [comment]
Looks like it is fixed. Thanks!

**Comment by github-account1111** [comment]
Fixed for me as well. Thanks very much Rustem.
