### ISSUE TITLE
Search from Address Bar

### ISSUE THREAD

**Issue by J0ssel1n** [raindropio/app#117]
Hello ! I was wondering why the search in the address bar of Raindrop favorites was not present. Thanks for your help.

**Comment by micmalti** [comment]
Same issue here with Firefox version 124.0.1, despite the [docs](https://help.raindrop.io/browser-extension/#search-from-address-bar) seemingly saying that it's a supported feature. If there's a way to activate this feature on Firefox, some guidance would be appreciated.

**Comment by exentrich** [comment]
<img width="784" alt="Screenshot 2024-04-17 at 18 19 29" src="https://github.com/raindropio/app/assets/1203812/d9879450-fb20-4df5-827d-511b1cf87ad2">

1. Install browser extension
2. Login
3. Type `rd` and then your search query, wait a second
