### ISSUE TITLE
[Bug] [Save] Cannot save URI without domain.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [raindropio/app#118]
> Saving error! Raindrop validation failed: link: url is invalid, domain: Path `domain` is required.

This means I cannot save links to sites using hostnames (`https://dsldevice/login.lp`) IP addresses (`ftp://RokeJulianLockhart.FTP@192.168.1.221:2121/`) or internal browser schemas, like `about:debugging#/runtime/this-firefox` (I've been using that a lot for dealing with https://community.bitwarden.com/t/how-to-get-autofill-to-identify-firefox-extension/62906/1?u=rokejulianlockhart) at https://app.raindrop.io/my/0/. This is becoming a significant annoyance.

**Comment by exentrich** [comment]
You can save first and second URL. Only `about:debugging...` is not supported.
Sorry no plans to support such URLs

**Comment by RokeJulianLockhart** [comment]
> Sorry no plans to support such URLs

@exentrich, why?

> Only `about:debugging` is not supported.

That's not quite true. Raindrop actually appears to block all custom URI schemas. This means that I can't save any of the entries from the Windows's `ImmersiveControlPanel` ("Settings" application)'s URI scheme documentation, like the undermentioned. [^1]

> |Settings page| URI |
> |-------------|-----|
> | Access work or school | ms-settings:workplace |
> | Email & app accounts  | ms-settings:emailandaccounts |

[^1]: [`github.com/MicrosoftDocs/windows-dev-docs/blob/d8cd038a6c00b1196b3b9bab88594b293db92efc/uwp/launch-resume/launch-settings-app.md#ms-settings-uri-scheme-reference`](https://github.com/MicrosoftDocs/windows-dev-docs/blob/d8cd038a6c00b1196b3b9bab88594b293db92efc/uwp/launch-resume/launch-settings-app.md#ms-settings-uri-scheme-reference:~:text=for%20a%20URI.-,ms%2Dsettings:,-URI%20scheme%20reference)

**Comment by exentrich** [comment]
Even if Raindrop support such URLs, they can't be clicked due to browsers security limitation.
Can you click on any of the links on this page? https://nimble-bristle-comte.glitch.me/

**Comment by RokeJulianLockhart** [comment]
> https://github.com/raindropio/app/issues/118#issuecomment-2561748283

@exentrich, I can't, because you're only thinking of `about:` (or `chrome://`) schema-prefixed URIs.

It *shouldn't* apply to others, like `ms-settings`, which are associated to an application via the OS or DE configuration application (`ImmersiveControlPanel` on Windows, and `systemsettings` on KDE Plasma ≥ 6).

**Comment by exentrich** [comment]
We have no plans to add support for such URLs because I’m not entirely certain if it has any security implications.
This is a very specific requirement from my perspective.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/raindropio/app/issues/118#issuecomment-2562660850

@exentrich, regular websites can already place these in their source, and the browser creates an explicit pop-up (if a default handler hasn't been assigned in the browser's configuration page) which the user must accept for the application to be invoked. Mozilla and Google have very much already mitigated any potential security concerns in their implementations.

The aforementioned OS configuration pages are mostly for situations like `explorer.exe` and `(New-Object -ComObject "Shell.Application").FileRun()`, which aren't web browsers but still support invoking URIs with non-HTTP schemas. Even in this case, `ms-settings:defaultapps` leaves most options unset by default. However, this doesn't apply anyway due to the aforementioned browser security functionality.
