### ISSUE TITLE
Tags not working as expected

### ISSUE THREAD

**Issue by wlsidlsi** [raindropio/app#120]
**Use Case**
Copy and paste tags into the edit tags field doesn't properly parse.

**Issue**

If I copy and paste  the below strings in tags it always treats as one tag.  Shouldn't have to hit enter for each tag.

sequence becomes string
#a #b #c  => "#a #b #c"
#a, #b, #c => "#a, #b, #c"
#a <press enter> #b < press enter> #c <press enter> => "#a" "#b" "#c"

**Expected Behavior**
I expect for it to parse the list of hashtags and treat as individual hashtags.  Hashtags, with space if allowed, should end with another hashtag to signal the space is meant to be included in hashtag.   Hashtags shouldn't have commas, colons, semicolons or other special characters.

**Comment by exentrich** [comment]
Fixed
