### ISSUE TITLE
Keyboard shortcuts in Windows Firefox do not work as expected

### ISSUE THREAD

**Issue by benji1304** [raindropio/app#121]
From here

https://help.raindrop.io/browser-extension/#tips--tricks

> Open browser extension  | Ctrl+Shift+E

This opens the Network tab in the dev console.

> Firefox only: the hotkey for save current page / highlight is Alt+Shift+S

This opens the History menu.

**Comment by runesoe** [comment]
Some experience here.

**Comment by jdrch** [comment]
Same problem here. Firefox Nightly x64 on Windows 11. Apparently the [solution](https://www.reddit.com/r/firefox/comments/yusp7s/comment/iwbcff3/) is to [add](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands#syntax) `_execute.action` to the extension's `manifest.json` file. Does anyone know where that file is located? I searched the repo and couldn't find it, which is odd because per Mozilla all add-ons are required to have it.

**Comment by jdrch** [comment]
Update: `Alt` `Shift` `B` works for me. Anyone else?

**Comment by benji1304** [comment]
> Update: `Alt` `Shift` `B` works for me. Anyone else?

Nope, on firefox that opens the bookmarks menu for me (same as pressing alt+B)

**Comment by jdrch** [comment]
> > Update: `Alt` `Shift` `B` works for me. Anyone else?
> 
> Nope, on firefox that opens the bookmarks menu for me (same as pressing alt+B or shift+B)

Welp, still waiting to hear anything at all about the fix I submitted.

**Comment by benji1304** [comment]
@exentrich  can you review?

**Comment by exentrich** [comment]
It appears that in the latest version of Firefox on Windows, our current shortcuts cannot be used for our extension. 

Could you suggest alternative shortcuts?
Here are some options I came up with, but I need your feedback:
- Open extension: Alt+Shift+R
- Save/highlight: Alt+Shift+A
- Open sidebar: Alt+Shift+Z

What do you think?

**Comment by jdrch** [comment]
> It appears that in the latest version of Firefox on Windows, our current shortcuts cannot be used for our extension. 
> 
> Could you suggest alternative shortcuts?
> Here are some options I came up with, but I need your feedback:
> - Open extension: Alt+Shift+R
> - Save/highlight: Alt+Shift+A
> - Open sidebar: Alt+Shift+Z
> 
> What do you think?

Those all work for me!

**Comment by benji1304** [comment]
i know this has been closed as completed but none of these shortcuts work for me on Firefox in windows

**Comment by azeveco** [comment]
Hey! The "Bookmark/Save highlight" shortcut doesn't work. Not even the default one.

There's no shortcut with the same combo. The "Open Browser extension" works without a problem, but the Bookmark itself doesn't.

For now, the workaround is to choose to open the extension as clipper, but still.. not good at all.
