### ISSUE TITLE
Highlight doesn't work on Github properly

### ISSUE THREAD

**Issue by taylankasap** [raindropio/app#125]
Steps:
1. Open https://github.com/raindropio/app
2. Highlight this text: "Mono repo for Raindrop.io web app, browser extension and desktop app"
3. Highlight this text: "Be sure to run npm i before calling any commands below"
4. Reload page just to make sure

Expected:
Both texts to be highlighted

Actual:
Even though both highlights are saved only the second text is highlighted

![image](https://github.com/raindropio/app/assets/4192479/889b2d98-0a3a-43c1-8bb3-4fd5b16842fd)

---

This is just an example and this issue happens on big chunk of Github.

**Comment by taylankasap** [comment]
Even though as far as I can see you don't welcome development contributions, I'm still offering it in case you change your mind.

**Comment by exentrich** [comment]
Fixed
