### ISSUE TITLE
Created date from import not showing properly

### ISSUE THREAD

**Issue by sw90036** [raindropio/app#127]
Hello -

After having them disappear again, I'm finally giving up on Edge Collections and I stumbled upon Raindrop.io, EXCELLENT APP!  I plan to upgrade to the Pro edition after I get a few things sorted out, in particular...

I just imported my Edge Collections and in the Raindrop app, the date/time for all of my links shows as the date/time that everything was imported, even though I did have a CREATED column in the CSVG file.  Here is a sample of the header row and two data rows:

![image](https://github.com/raindropio/app/assets/44692292/9b8f8f3f-0503-436b-8da3-2ccf214cbc69)

Any ideas on how to fix this?  

Thank you!

**Comment by exentrich** [comment]
Make sure to use date format that JS can parse:
- `YYYY-MM-DDTHH:mm:ss.sssZ`
- or timestamp, for example `628021800000`
