### ISSUE TITLE
Chrome Raindrop.io Side Panel closes after clicking on link

### ISSUE THREAD

**Issue by jfgosselin** [raindropio/app#129]
**Describe the bug**

A recent update of Chrome has removed remove the Side Panel from the toolbar. As result this documentation is no longer valid https://help.raindrop.io/browser-extension/#side-panel .

To bring back the Side Panel from the toolbar the following flag chrome://flags/#side-panel-pinning must be disabled.

Or right click on the Raindrop.io extension and select "Open sidebar".

The bug is that when clicking on link from the Raindrop.io Side Panel , the Side Panel closes immediately after opening the link. In contrast the "Bookmarks"  Side Panel from Chrome doesn't closes when you click on a link

**To Reproduce**
1. Right click on the Raindrop.io extension
2. Click on 'Open sidebar'
3. Click on a link
4. The Side Panel will close immediately

**Expected behavior**
The Raindrop.io Side Panel should be sticky.

**Desktop (please complete the following information):**
 - Device: Apple M1 Pro
 - OS: macOS Sonoma 14.4.1 (23E224)
 - Browser : Chrome 124.0.6367.202 (Official Build) (arm64)
 - Raindrio.io Version  5.6.27

**Comment by exentrich** [comment]
Thanks for bug report! I published an update with a fix, will be available in next few hours

**Comment by jfgosselin** [comment]
@exentrich did you push a new Chrome extension ? I don't see any updates.

**Comment by exentrich** [comment]
Yes update with fix is 5.6.28 https://chromewebstore.google.com/detail/raindropio/ldgfbffkinooeloadekpmfoklnobpien
