### ISSUE TITLE
Which versions have the Edit function?

### ISSUE THREAD

**Issue by LorenAmelang** [raindropio/app#130]
In https://help.raindrop.io/bookmarks#appearance I see: 
Add note
You can add notes to your items already uploaded to Raindrop.io by clicking onto the Edit button.

I can't find that button in the web view of Raindrop, or in the iOS app versions. Is it only in the desktop app? 

I'd just install that, but last time I tried to get my Arch Linux to use Snap, I wasted most of a day and it never worked. 

Guess I can add notes and tags while initially saving the link, but sometimes I want to fix those later...

Also...  Could there be a default note showing which device saved the link originally? I often want to go back into browser history to find related content.

**Comment by exentrich** [comment]
You can configure visible buttons here https://app.raindrop.io/settings/app (Buttons)
Other way to edit: right click and select Edit
On iOS swipe to left
