### ISSUE TITLE
Tag & Collection Suggestions Not Working

### ISSUE THREAD

**Issue by organicveggie** [raindropio/app#131]
The first item in the changelog for 5.6.24 (Apr 25, 2024) says:

> New ✦ AI-Driven Collection and Tag Suggestions (Pro Only): When adding or editing an unsorted bookmark, you'll now see AI-generated suggestions above the collection and tag fields.

After upgrading to Pro, I don't see suggestions above the collection or tag fields when adding a new bookmark or editing an existing bookmark.

**To Reproduce**

1. Upgrade to Pro
2. Open Chrome
4. Go to my unsorted bookmarks: https://app.raindrop.io/my/-1
5. Highlight any bookmark in the list
6. Click `Edit`
7. Click on the `Tags` field
8. No suggestions displayed
9. Click on the `Collection` dropdown, which displays the `Select collection` popup
10. No suggestions displayed
11. Navigate to a page like https://help.raindrop.io/changelog/
12. Click the Raindrop.io Chrome extension icon, which displays the `New` popup
13. Click on the `Tags` field
14. No suggestions displayed
15. Click on the `Collection` dropdown, which displays the `Select collection` popup
16. No suggestions displayed

**Expected behavior**

When adding or editing and I expect to see a one or more suggested  tags listed directly above the `Tags` field.

When adding or editing and the `Select collection` popup is displayed, I expect to see a one or more suggested  collection names.

**Screenshots**

<img width="559" alt="image" src="https://github.com/raindropio/app/assets/861927/c206e3ee-d03d-4725-82ba-18adf8d49104">

<img width="496" alt="image" src="https://github.com/raindropio/app/assets/861927/2a1f7998-99a4-4b09-acb6-def0985d4a7b">

**Desktop (please complete the following information):**
 - OS: macOS 14.4.1 (23E224)
 - Browser Chrome 124.0.6367.158 (Official Build) (x86_64)
 - Version: 5.6.27

**Comment by exentrich** [comment]
Ensure that our AI only suggests your existing collections and tags. It never generate new ones, as these tend to be too generic and not very useful. You need to create some collections and tags, and apply them to a few bookmarks. After this, the AI will adapt to your organizational style and make suggestions accordingly.
Learn more https://help.raindrop.io/ai-suggestions
