### ISSUE TITLE
Icons are not displayed properly

### ISSUE THREAD

**Issue by QiQi777iii** [raindropio/app#137]
**Describe the bug**
Favorite web page, icon cannot be loaded

**Screenshots**
![image](https://github.com/raindropio/app/assets/141505720/511e0073-9542-44d9-89ff-fefb7d00048e)

**Desktop (please complete the following information):**
 - Browser [chrome]
 - Version [126.0.6478.114]

**Additional context**
Like the image above, some web pages have icons on the tab but they fail to load properly, resulting in a blank space. I'm thinking of uploading the icon myself, but even after I uploaded the last time, the previous icon won't update. It's really confusing for me.

**Comment by exentrich** [comment]
Hello!
This website https://ping.ceo/ ? It doesn't have a favicon, even in when opened in the browser
<img width="129" alt="Screenshot 2024-06-20 at 15 38 24" src="https://github.com/raindropio/app/assets/1203812/18736e88-6754-4f6d-ae91-b1a5e04380ea">

You want to see the same glob instead of grey rectangle?

**Comment by QiQi777iii** [comment]
The link I provided is wrong, sorry
![image](https://github.com/raindropio/app/assets/141505720/0daaf3dd-6912-4701-bffc-4a300e1d0a25)
This website is designed with icons, but they fail to load properly, resulting in this effect.
![image](https://github.com/raindropio/app/assets/141505720/d8d3ae13-27c9-49e7-9ee0-9f68d0c196be)
It will look like the above picture, I don't know if it's because it didn't get it successfully, or what

**Comment by QiQi777iii** [comment]
Some of my favorite websites are like this. They have icons but cannot be loaded.

**Comment by exentrich** [comment]
Thanks, definitely a bug. Please provide all URLs to websites with broken favicons. This will help fixing all of them

**Comment by exentrich** [comment]
Check again please, should be fixed now

**Comment by QiQi777iii** [comment]
I've seen it, a lot of it is back to normal, but there's still one site from my favorites that isn't showing up, here's the url to the site, could you please look at it again?
https://containrrr.dev/watchtower/
