### ISSUE TITLE
Got error when running on Local Machine !!

### ISSUE THREAD

**Issue by harshdave161** [raindropio/app#14]
When We Run It on Local machine using yarn local and then it serves on localhost:2000 and open up but when we try to sign in !! this giving error like Failed to fetch http://localhost:3000/v1/auth/email/login
![image](https://user-images.githubusercontent.com/40320848/115964827-ea772200-a543-11eb-8c42-20a5050728b3.png)

i think so back end server where apis are running is not present in code ?? can some one help please !!

**Comment by ElevonsJKeloids** [comment]
@exentrich, do you plan on opening up the back-end code? or will it remain closed? 

I believe that opening the source will lead to a great deal of innovation in this project, and would encourage developers to contribute to make raindrop even better.

**see also: #11**

**Comment by exentrich** [comment]
Change API_ENDPOINT_URL to just https://api.raindrop.io in src/data/constants/app.js
