### ISSUE TITLE
Highlighting Feature - Disappear

### ISSUE THREAD

**Issue by loririi** [raindropio/app#140]
**Describe the bug**
Highlights continue disappearing, and there is no more a color that let you see the text.

**To Reproduce**
1. Go to a page with text
2. Make a highlight
3. Highlight disappear

**Expected behavior**
Highlighting feature had no problems for me until the last update. The highlights didn't disappear (occasionaly they disappeared sometimes, but not literally every time like now) and all the colors were clear and visible.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 126

**Smartphone (please complete the following information):**

**Additional context**

**Comment by exentrich** [comment]
Do you have Dark Reader extension?
This happen on any page or specific? Can you send me a link to a page and what text you try to highlight and it disappear

**Comment by loririi** [comment]
Yes I have dark reader on chrome. 

The disappearing and the color blurring happen in any page I try to highlight. 

After removing dark reader the highlighted text became like before the update. But the disappearing error still occurs, so I guess it's not dark reader that cause the problem. 

Is it possible make the highlighting feature robust to dark modes or dark mode extensions? I really like to read preserving night mode, I had dark reader before the extension update and it was working fine.

**Comment by exentrich** [comment]
Dark Reader support is improved in latest update of Chrome extension.
Go to `chrome://extensions/` (copy and paste to address bar) and click `Update`

To fix disappearing issue, please provide steps to reproduce:
1. URL of the page
2. What text you try to highlight

**Comment by loririi** [comment]
I tested on a new browser and the disappearing issue didn't occur, so I suppose it's a conflicting extensions problem, I'm sorry, I try to remove the error extension.

Regarding Dark Reader, I updated it as you said, but the highlighting colors remain the same as the screenshot below. Am I missing something?

<img width="652" alt=" " src="https://github.com/user-attachments/assets/dac98dc9-3afc-488c-b213-c46ed9a7f701">

**Comment by exentrich** [comment]
@loririi what URL of the page?

**Comment by loririi** [comment]
> @loririi what URL of the page?

[https://techcrunch.com/2024/07/22/the-scene-app-matches-new-yorkers-with-restaurants-bars-clubs/](https://techcrunch.com/2024/07/22/the-scene-app-matches-new-yorkers-with-restaurants-bars-clubs/)

But the colors are the same in any page with dark reader, not specifically this webpage

**Comment by exentrich** [comment]
Go to chrome://extensions/ (copy and paste to address bar)

What Raindrop.io extension version you have?

<img width="317" alt="Screenshot 2024-07-23 at 16 30 50" src="https://github.com/user-attachments/assets/06014953-06ad-4ca5-96fc-07b18e9fd818">

**Comment by loririi** [comment]
I have 5.6.51

**Comment by exentrich** [comment]
Very strange, because I can't reproduce this bug
<img width="853" alt="Screenshot 2024-07-23 at 16 39 36" src="https://github.com/user-attachments/assets/1076e009-a271-44ac-97c1-0ff4b5adc76f">

**Comment by loririi** [comment]
Unfortunately I didn't get the same colors result. Is it all together different from the previous highlight colors? Because I remember they were clear before, they didn't change the text color itself?

I also have forced dark mode on macOS and browser itself, could that also be a source of problem?

**Comment by loririi** [comment]
This is my result with dark reader off

<img width="640" alt=" " src="https://github.com/user-attachments/assets/b8ae2b88-e924-40d2-9d43-e8b7dbc214d8">

**Comment by loririi** [comment]
Hi, is everything okay? Have I said something wrong?

**Comment by exentrich** [comment]
Tried the same page on mac and Windows and I can't reproduce your bug :(
Is it happen in Chrome? Maybe you have some other extensions that can change text color?

**Comment by loririi** [comment]
Can you please try with Dark Reader and this chrome://flags/#enable-force-dark with the option Enabled with simple HSL-Based Inversion?

<img width="736" alt="     " src="https://github.com/user-attachments/assets/e7b7b1d0-142d-41e1-a06b-5d78563a8b42">

I'm pretty sure that's the problem because when I disable this option, the highlight is normal. 

Is it possible to make the highlight resilient with this browser dark mode? I mainly use Chrome, but it is enabled by default in browser like Brave.

**Comment by exentrich** [comment]
Do you really need Auto Dark Mode? Dark Reader is not enough? I'm just curious what the use-case.
No idea how to fix this, because this flag invert all colors on the page, plus Dark reader is trying to do the same thing.
Probably there other flag that can make this situation even crazier.

**Comment by loririi** [comment]
I need auto dark mode to darken hard sites (generally better to darken any site) and protected sites by chrome like chrome webstore or new tab page.

I was previously using highlighter with auto dark mode on and the highlight color was normal. Would there be a problem to use the previous color of the highlighter?

**Comment by exentrich** [comment]
Unfortunately I have no idea how to fix such rare edge case
