### ISSUE TITLE
Can't highlight Turkish letter İ (dotted I)

### ISSUE THREAD

**Issue by taylankasap** [raindropio/app#141]
**To Reproduce**
1. Go to 'https://tr.wikipedia.org/wiki/%C3%87okludo%C4%9Frusal_harita'
2. Select the word 'İki' in the beginning of the second paragraph
3. Right click and click 'Save highlights'

**Expected behavior**
The word 'İki' should get highlighted.

**Actual behavior**
The word 'İki' gets saved to the highlights, but the word itself on the page is not highlighted.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 127.0.6533.72 (Official Build) (64-bit)

**Comment by exentrich** [comment]
Thanks for bug report! Will be fixed in upcoming update
