### ISSUE TITLE
Keyboard Shortcut in Safari conflicts with Responsive Design mode

### ISSUE THREAD

**Issue by tkoenig** [raindropio/app#149]
**Describe the bug**
I use Safari for development, so the Keyboard Shortcut for  "Enter Responsive Design Mode" (ctrl-cmd-R) is essential for me. Recently (Sonoma?) this now opens the raindrop modal, and there is no way to change this other than disabling the extension?

**To Reproduce**
1. Make sure  "Show features for web developers" is checked in Settings -> Advanced in Safari
2. Press ctrl-cmd-R 
3. The raindrop extension modal is shown

**Expected behavior**

The Responsive design mode feature in Safari should be enabled.

**Screenshots**
<img width="528" alt="Screenshot 2024-10-01 at 18 31 07" src="https://github.com/user-attachments/assets/9c0ac729-9870-4ec5-9c02-1b2a002360d4">

**Desktop (please complete the following information):**
 - OS: Mac OS 15.0 (24A335)
 - Browser: Safari
 - Version 18.0 (20619.1.26.31.6)

**Comment by exentrich** [comment]
Hello! 
Apologies for the inconvenience. 
A fix is on the way, and you can expect it soon (depending on the App Store review speed). 

I aimed to unify shortcuts across all browsers but overlooked some edge cases. 
The new shortcut for saving a bookmark or highlight is `Cmd+Shift+S`. Will be no additional shortcuts in the Safari extension.
