### ISSUE TITLE
Bookmarking from Amazon Music is now broken

### ISSUE THREAD

**Issue by empedia** [raindropio/app#151]
**Describe the bug**
I have been using Raindrop for several years and one of the things which I have used it for most heavily is bookmarking albums from Amazon Music which has worked extremely well until recently- Raindrop correctly captured the Cover Art, Title and Artist perfectly but now this seems to be completely broken.

**To Reproduce**
1. Go to https://music.amazon.co.uk/albums/B09CBK45SS
2. Click on the share link
3. Copy the URL 
4. Add the URL as a bookmark in Raindrop

**Expected behavior**
A bookmark to the page which captures the artist, album and cover art is created.

** Actual behavior**

Bookmark for the URL is created, the album art is not captured, a thumbnail of the whole page is generated instead, the album name and title are completely missing - instead the album ID is used for the title of the bookmark - e.g. B09 cbk45 ss

**Screenshots**

Captured album from August 6th shows perfect details
Captured album from August 30th is completely broken

![image](https://github.com/user-attachments/assets/823d8239-0fb9-44a8-b17f-ff1d52b70efb)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Microsoft Edge
 - Version 130

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: Android 14
 - Browser N/A

**Additional context**

**Comment by exentrich** [comment]
I improved amazon music parsing. All new bookmarks will have a correct title, description and thumbnail.
To fix old one just remove them and add again

**Comment by empedia** [comment]
Unfortunately it seems this issue has reappeared. Could you please take a look.  Many thanks.

**Comment by exentrich** [comment]
Sorry about that, fixed now
