### ISSUE TITLE
[BUG] The latest version of Firefox's Strict ETP prevents Raindrop.io extension from signing in to the account.

### ISSUE THREAD

**Issue by Iz-zzzzz** [raindropio/app#152]
**Describe the bug**
The latest version of Firefox's Strict ETP prevents Raindrop.io extension from signing in to the account.

**To Reproduce**
1. Create new Firefox profile
2. Install extension
3. Sign in
4. Click at extension
5. Prompt to sign in again

https://github.com/user-attachments/assets/d221859e-2619-4857-9934-f65e7a0d1c3e

**Expected behavior**
Can sign in to the account as before.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox 132.0 (64-bit)

**Additional context**
1. I don't sure whether this issue should be opened here or Bugzilla.

2. Latest change related to this issue
> Firefox now blocks third-party cookie access when Enhanced Tracking Protection's Strict mode is enabled.

[source](https://www.mozilla.org/en-US/firefox/132.0/releasenotes/#:~:text=firefox%20now%20blocks%20third-party%20cookie%20access%20when%20enhanced%20tracking%20protection's%20strict%20mode%20is%20enabled)

3. Changing ETP mode from `Strict` to `Standard` solves this issue.

4. ETP stands for `Enhanced Tracking Protection`

**Comment by exentrich** [comment]
Update with fix is on the way. Waiting for review from Mozilla. They usually approve update in few days, up to a week.
In the mean time just add api.raindrop.io to cookies whitelist:
1. Open settings. Go to Privacy & Security section. Scroll to Cookies and Site Data and click Manage Permissions...
2. In Address of website put https://api.raindrop.io and click Allow. Then click Save Changes

**Comment by jakeparis** [comment]
> Update with fix is on the way. Waiting for review from Mozilla. They usually approve update in few days, up to a week. In the mean time just add api.raindrop.io to cookies whitelist:
> 
>     1. Open settings. Go to Privacy & Security section. Scroll to Cookies and Site Data and click Manage Permissions...
> 
>     2. In Address of website put https://api.raindrop.io and click Allow. Then click Save Changes

@exentrich Thanks so much for the work around!

**Comment by baumheld** [comment]
> Update with fix is on the way. Waiting for review from Mozilla. They usually approve update in few days, up to a week. In the mean time just add api.raindrop.io to cookies whitelist:
> 
>     1. Open settings. Go to Privacy & Security section. Scroll to Cookies and Site Data and click Manage Permissions...
> 
>     2. In Address of website put https://api.raindrop.io and click Allow. Then click Save Changes

At least for me this workaround is not doing the trick. 
The last firefox extension was updated on 19th of November 2024
I guess I have to wait

**Comment by exentrich** [comment]
@baumheld try to uninstall and install Raindrop extension. Tested on clean Firefox with Strict ETP and latest Raindrop extension is working fine
