### ISSUE TITLE
[BUG] In the last version 6.6.62 shortcut to open extension menubar stopped working in FF

### ISSUE THREAD

**Issue by natrim** [raindropio/app#155]
**Describe the bug**
In the last version (6.6.62) shortcut to open extension menubar stopped working in FF

**To Reproduce**
1. Go to 'about:addons'
2. Click on 'Set shortcuts'
3. You will se that the option to open the Shortcut extension menu has disappeared

FF 132.0.2 (aarch64) MacOS 15.1
Extension v6.6.62

![obrazek](https://github.com/user-attachments/assets/a56bd5c1-2c73-49e4-a210-0b06a5bb05f7)

---

in ext version 6.6.24 the option to add shortcut was still here

![obrazek](https://github.com/user-attachments/assets/7eed0cea-471f-4f52-9257-06ad2bc00e5d)

**Comment by blancpain** [comment]
Noticed this as well - very useful shortcut, would be great if it can be brought back!

**Comment by natrim** [comment]
happened here:
https://github.com/raindropio/app/commit/4d7a9b91b871ccab86ab46c75e0c1fb34b5104a7#diff-a04d69f11d2d98c1da1015be3b71c3ab879c612f0e86d18040ce4916110667ffL130

the removal of _execute_action

**Comment by piasnikj** [comment]
Agreed.  Not sure why this would be removed.

**Comment by exentrich** [comment]
Sorry for the inconvenience.
Update with a fix is on the way. Hope Mozilla approve update soon

**Comment by exentrich** [comment]
Restored in latest update

**Comment by eissar** [comment]
For anyone else with this issue right now, I was having this issue on firefox (waterfox)/ windows 11. on the firefox addons store, the last raindrop update has release date 2024-12-17. After downloading the firefox-prod.zip from releases, and I started getting error: 'Raindrop validation failed: link: url is invalid, domain: Path `domain` is required.' in the popup window. Downloading an older version from firefox addons seems to work. https://addons.mozilla.org/firefox/downloads/file/4137161/raindropio-6.6.12.xpi
