### ISSUE TITLE
OAuth switchover at `raindropio.canny.io` to `app.raindrop.io/account/login` has rendered log-in to `raindropio.canny.io` accounts registered via `canny.io/login` impossible.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [raindropio/app#157]
**Describe the bug**

The OAuth switchover at [`raindropio.canny.io`][1] to [`app.raindrop.io/account/login`][2] has rendered logging in to [`raindropio.canny.io`][1] accounts registered via [`canny.io/login`][3] impossible.

Instead, I am forced to log in with my [`app.raindrop.io/account/login`][2] account, meaning that I am unable to modify past comments and subscriptions (etcetera) with my [`canny.io/login`][3] account.

[1]: https://raindropio.canny.io/
[2]: https://app.raindrop.io/account/login
[3]: https://canny.io/login

**To Reproduce**

Attempt to log in at [`raindropio.canny.io`][1].

**Expected behavior**

I should be able to login with either the [`app.raindrop.io/account/login`][2] or [`canny.io/login`][3] OAuth providers.

**Desktop (please complete the following information):**

- OS: [`Fedora-KDE-Live-x86_64-41-1.4.iso`](https://download.fedoraproject.org/pub/fedora/linux/releases/41/Spins/x86_64/iso/Fedora-KDE-Live-x86_64-41-1.4.iso)
- Browser Version: [`firefox-133.0-2.fc41.x86_64.rpm`](https://fedora.pkgs.org/41/fedora-updates-x86_64/firefox-133.0-2.fc41.x86_64.rpm.html)

**Comment by exentrich** [comment]
To be able to login to your old Canny account, make sure your Raindrop account have the same email.
Register a new account on Raindrop if you not used this email previously.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/raindropio/app/issues/157#issuecomment-2560996431

@exentrich, I utilize a different e-mail address provided by [`app.addy.io/aliases`](https://app.addy.io/aliases?search=raindrop) for each service. It's how my e-mail account routes its mail. I receive sometimes hundreds of messages via e-mail per day. Without it, I wouldn't be able to keep atop them.

Regardless, this isn't a particularly unique configuration. There's a reason that OAuth2 tends to be utilized in the stead of cross-account user information correlation - it's significantly more reliable.

**Comment by exentrich** [comment]
We migrated to login through Raindrop due to Canny’s inadequate spam protection, which allowed spammers to flood the entire board with their spam content.
The only way to utilize your existing account, as previously mentioned, is to ensure that both emails are identical.
Regrettably, if this is not feasible, I am unable to provide any alternative workarounds.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/raindropio/app/issues/157#event-15756226230

@exentrich, as a helpful note of advice, you don't actually have to reopen an issue to comment. There should be separate buttons. Additionally, it might be worth closing this as unplanned instead of completed.

**Comment by exentrich** [comment]
I accidentally clicked “reopen,” and I believe the issue is resolved because I mentioned a simple workaround :)
