### ISSUE TITLE
Don't force lowercasing in new tags

### ISSUE THREAD

**Issue by twjordan** [raindropio/app#16]
I recently noticed that when I create a new tag with the chrome plugin on MacOS that the tag is forced to lowercase.

I believe all search, etc should be case insensitive, but casing of tags should be preserved as the user wants to edit it. Many of my tags are locations and it helps to distinguish a city name from a topical tag to have the correct casing.

**Comment by exentrich** [comment]
Sorry about that. Fix is on the way
