### ISSUE TITLE
Firefox Extension, Containers Support

### ISSUE THREAD

**Issue by matt22207** [raindropio/app#21]
Hi,

I use two extensions to try to maintain (extra) privacy in Firefox:

- `Firefox Multi-account Containers` which allows you to create new tabs in isolated containers (as well as persist certain sites into specified permanent containers) - https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/
- `Temporary Containers` which ensures that all new tabs go into an isolated "temporary" container (unless they match the site list for permanent/persistent containers above) - https://addons.mozilla.org/en-US/firefox/addon/temporary-containers/

These 2 ensure that unless I assign a persistent container that any site will not store cookies/localstorage/etc long term, or be able to persist cookies/storage across sites, etc.

I keep the `raindrop.io` site assigned to a permanent `Raindrop` container so that manually browsing the site (outside of the extension) maintains login/etc long-term. Today the Raindrop firefox extension logged me out of my account and it took a while to figure how to log back in. Clicking on login from the extension took me to my proper container which is already logged in. However the extension still can't access the login credentials/cookie from the container.

It looks like extensions can't run from inside containers. So I needed to login again outside of any container.

To get around this, I had to :
- Unassign raindrop.io from my permanent container (which will allow me to use the site outside of any container)
- Disable `Temporary Containers` (so new tabs don't go into any container)
- Start a new tab that is outside of containers, and login to raindrop. (This temporarily fixes the problem and allows the extension to remain logged in for however long the session lasts.)
- Re-enable `Temporary Containers` & Re-assign raindrop.io to my `Raindrop` permanent container

So this should last me until my raindrop extension's session expires again, but is there any better way to do this without disabling my container extensions? Any way for the extension itself to either run in my permanent container, or have the extension access that container via a browser API?

**Comment by chkrde** [comment]
Hi,

I'm having trouble with Firefox app login and containers, too. Since i use [Sideberry](https://addons.mozilla.org/de/firefox/addon/sidebery/), which requires containers, i would have to disable Sideberry before using the workaround described by @matt22207 

A workaround which worked before was copying cookies with [Cookie Quick Manager](https://addons.mozilla.org/de/firefox/addon/cookie-quick-manager/) from the context where i'm logged in to default context (in which the app runs). But this doesn't seem to work now.

**Comment by exentrich** [comment]
Fixed in recent updates. Let me know if still happens.
Make sure to reinstall Raindrop Firefox extension.

... wow Firefox is going crazy with so many privacy "enhancements": ETP, Firstparty Isolate Mode, Containers...

**Comment by ringods** [comment]
... because Chrome & Edge don't care a cent about your privacy.
