### ISSUE TITLE
Cover images forbidden

### ISSUE THREAD

**Issue by devhims** [raindropio/app#23]
Hey,

I'm using the Raindrop API in a NextJs project. However, most of the "cover" images are now returning as forbidden or generated link is broken

Broken: https://media-exp1.licdn.com/dms/image/C5605AQFhi0TarwnXkA/videocover-high/0/1616315566270?e=1622725200&v=beta&t=L0hTwpLHM8TLa6NKeSsjKoMOvMz-49IeqQ-PIuvg0DE

Normal: https://dms.licdn.com/video-thumbs/C5105AQEa4zE1iiW8Kw/ad0cb9fc16bc4fc5ac31ee81f76272fd/feedshare-videocover_high-captions-thumbnails/1280x720-00001.jpg

Can anyone help me resolve this issue? It was working fine till yesterday.

**Comment by exentrich** [comment]
Hello!
As you can see this url's are from Licdn.com domain, not from Raindrop.io. Contact with Licdn.com support to resolve this issue

**Comment by devhims** [comment]
Hi @exentrich, both the URLs are returned when querying my collection with the Raindrop API. And they are fine when I check them in the app view on Raindrop.io

Anyway, I had to upload new cover images manually to resolve the issue.
