### ISSUE TITLE
Chrome Extension stopped working as Save, and now only shows the browser

### ISSUE THREAD

**Issue by fserb** [raindropio/app#24]
It used to be that when I clicked on the raindrop.io extension, I'd get to a pop up to save the current page as a bookmark (choose category, etc). 
Now, when I press on it, it shows a little browser very similar to the main raindrop website.
I'm not sure what I've changed, but I really really like the other behaviour. I always have Raindrop open. I don't use the extension to browser, only to save.

Is there a way to get the old behaviour back?

**Comment by exentrich** [comment]
You need to enable **Clipper** mode in settings https://help.raindrop.io/browser-extension#appearance

**Comment by fserb** [comment]
Yeah, I had done that before.
I think with the latest Chrome update, the extension lost its settings. And there was no way to get back to that page (it should probably register the extension Options).

I uninstalled the extension and installed again, and the settings page showed up. :) thanks.
