### ISSUE TITLE
Filters and Tags no longer working

### ISSUE THREAD

**Issue by subz390** [raindropio/app#25]
![210815-122059](https://user-images.githubusercontent.com/11546815/129479455-4bf452d6-41a5-4225-9f0d-7d984f19728a.png)

I'm getting the above error in both Chrome and Firefox on Filters, Tags and from the search box results - in both the app and browser extension.
Collections are showing bookmarks as expected.
Refreshing does nothing.

Version: `Raindrop.io 5.4.2`

**Comment by subz390** [comment]
Started working again

**Comment by subz390** [comment]
I found how to replicate the error:
When filtering `by name`, search results, `filters` and `tags` display the error.

![210816-040505 filtering by name](https://user-images.githubusercontent.com/11546815/129506155-cef4d474-a508-45cb-a08a-4542ec41dcec.png)

To reverse the issue, clear the search to display all bookmarks, then select any other filtering option except `by name`.

![210816-041033 reset the filter](https://user-images.githubusercontent.com/11546815/129506675-de4e9bca-8222-4927-8bc3-7579e8a6954a.png)

**Comment by cidrei** [comment]
I'm having the same issue with any link that existed before today. Searching for an item by name or tag or anything returns no results. If you edit the link in any manner that requires it to update, even something simple like adding or removing it from favorites, it will start appearing in search results again. It seems like an index file is missing or corrupt or something to that effect.

**Comment by bsitruk** [comment]
I'm having the same issue.
Filtering by labels returns no results.

**Comment by risk00** [comment]
I am still experiencing this issue in Jan 2022. Changing Sort order as described above does not fix the issue. Please advise.

**Comment by risk00** [comment]
Error now gone after showing up in Chrome and Firefox.
