### ISSUE TITLE
Feature Request: Duplicate a set of existing tags (from existing bookmark) during creation of a new bookmark

### ISSUE THREAD

**Issue by realmarkcross** [raindropio/app#28]
I often save several related pages that have the same tags applied, one after the other (same line of research on a topic) and it would be convenient to be able to duplicate a set of tags that I've already attached to an existing bookmark during the creation of a new bookmark.  It's kind of a pain to have to remember which tags I used in the prior bookmark and then reattach those to the new bookmark, especially when there are multiple new pages being added that would have the same set of tags.

**Comment by exentrich** [comment]
Please add to https://better.raindrop.io/feature-requests
