### ISSUE TITLE
Strip the "?utm..." part from links automatically

### ISSUE THREAD

**Issue by mortenbjoern** [raindropio/app#3]
This is a thing that has bothered me for a long time... it might be pretty niche problem but I would love if links where saved without the added parameters.

**Comment by levesduzw** [comment]
Try [ClearURL](https://github.com/ClearURLs/Addon)!

**Comment by KlausDevWalker** [comment]
> Try [ClearURLs](https://github.com/ClearURLs/Addon)!

Great suggestion! Thanks :)

**Comment by exentrich** [comment]
Please add to https://better.raindrop.io/feature-requests
