### ISSUE TITLE
URL files are saved with an error message if I drag & drop them

### ISSUE THREAD

**Issue by GrumpyNyanCat** [raindropio/app#31]
Hi, 

I got the attached error message when I'm dragging and dropping URLs out of Chrome into a Chrome Window with raindrop open, or into a chrome web-app window of raindrop. 
The error message is not showing up, if I'm using the desktop app installation of raindrop. 

I'm always using drag & drop to save bookmarks into raindrop, so this error message is kind of annoying.
In the end, the drag & dropped URL link is saved anyway, so this error message is showing up, although the link is saved successfully. 

Did chrome changed something, which is causing this issue?

Thank you very much and have a nice day

T.A.

![Screenshot1](https://user-images.githubusercontent.com/37424484/144011197-7a941df1-1b1d-49d2-a6bb-0abb26e032a3.jpg)
![Screenshot2](https://user-images.githubusercontent.com/37424484/144011203-2d51da15-c9ba-475e-96c2-8329539d1105.jpg)

**Comment by exentrich** [comment]
It's weird behaviour of some Chrome versions. Many users reported that in latest Chrome there no such issue. Can you confirm?

**Comment by GrumpyNyanCat** [comment]
Hi. Sorry, I completely forgot that I opened a Github Issue, too. Yeah! The bug is gone with the latest Chrome update. I think that this can remain closed. Thank you very much. 👍
