### ISSUE TITLE
[suggestion] Removing "buy the pro" ad...

### ISSUE THREAD

**Issue by stlsht** [raindropio/app#33]
Hey! Firstly, of course - I love your app. And I'm grateful that I can use it for free. 
I really want to pay for this app. But I cannot afford it for now. And I'm aware that there's a paid version - it's kinda freaky when I see this reminder all the time. 
IMHO this ad is not helping either me or you - it's not changing anything for now. I'm kinda aesthetic guy and I really want to have a clean feeling - that's why I love chose Raindrop. I want to stick with it. And this ad is the only thing that bother's me here - this ad, all the time on the sight.

**Suggestion:** I could afford one-time payment (5-7$) for just removing this ad and stick with free version. Maybe this option could be a win-win situation? What do you think?

I really want to help this project - and I will do it when I will have enough money. Would be super cool if you could change it, because it makes me think that I'm using not a free version but DEMO version and I feel really bad about it... don't want to feel like that.

**Comment by exentrich** [comment]
Raindrop in Free version doesn't have any ads except this one. I can't remove it, because it has very good convertion rate.
And this is only one place where I promote Pro subscription. I tested convertion rate in the past without this ad, and it dropped significantly.
Maybe I will make it smaller in the future, but for now I can't do much with it.

**Comment by stlsht** [comment]
>  I can't remove it, because it has very good convertion rate.

Huh. Too bad... and also - it's good to hear that, actually. I'm happy for you that it's working. 
... but maybe a hidden onetime payment? Oh, sorry - just trying :)
