### ISSUE TITLE
Blurry texts and icons when moving a bookmark to another collection

### ISSUE THREAD

**Issue by AlbertoFabbri93** [raindropio/app#35]
This happens in both the web and desktop apps. Screenshot:
![Screenshot 2021-12-18 231236](https://user-images.githubusercontent.com/51910894/146656958-978bfe76-aaf1-4fa3-9bfc-d12671a313a8.jpg)

**Comment by exentrich** [comment]
I don't understand issue. Can you share more details?

**Comment by AlbertoFabbri93** [comment]
Yes, basically every time I try to move a bookmark to another collection with the following button:
![Screenshot 2021-12-28 124540](https://user-images.githubusercontent.com/51910894/147563127-2ad3fd90-e789-4ad9-aba8-86522a3887fb.jpg)
the list with all my collections open but the icons are very blurry like if they were in low resolution but, I know that that is not the case because the icons are perfectly fine in all other menus.

**Comment by AlbertoFabbri93** [comment]
Did you find the bug?
