### ISSUE TITLE
Scroll to collection

### ISSUE THREAD

**Issue by exdeniz** [raindropio/app#36]
Previously, when you opened the mini-app collections scrolled to the current one, now this does not happen. You can add this behavior by default or by setting it in the extension. 
Tested on FF and Safari

**Comment by exentrich** [comment]
Hello!
Sorry about that. Fixed in 5.4.16

**Comment by exdeniz** [comment]
Ура! Это наконец-то работает. Спасибо, а то я уже черт знает сколько мучался.
