### ISSUE TITLE
Add a button to cancel the bookmark

### ISSUE THREAD

**Issue by coastaldemigod** [raindropio/app#38]
Since the extension repository has been archived, thus I'm commenting here.

When adding a bookmark via the extension for chrome, there is no "cancel" button.
A "cancel" button would be nice to have, in cases where you might have accidently pressed the extension and/or you may change your mind.

Moreover, if you think that this is "nice to have" feature but not something you would want to work on right now, I can help you in developing it, if you can assign it to me.

**Comment by exentrich** [comment]
Cancel == Delete
