### ISSUE TITLE
ActivityPub / Fediverse integration

### ISSUE THREAD

**Issue by xplosionmind** [raindropio/app#41]
It would be awesome if Raindrop could support [ActivityPub](https://activitypub.rocks) and become the first ever bookmarks manager to become part of the wonderful [Fediverse](https://en.wikipedia.org/wiki/Fediverse '“Fediverse” on Wikipedia').

**Comment by crazyyzarc** [comment]
> It would be awesome if Raindrop could support [ActivityPub](https://activitypub.rocks) and become the first ever bookmarks manager to become part of the wonderful [Fediverse](https://en.wikipedia.org/wiki/Fediverse).

What would that look like, what is the added value?

**Comment by xplosionmind** [comment]
> What would it look like

It would look like a social media where instead of posts you see and you publish saved articles with notes and highlights

> What is the added value?

It would enable a greater freedom for users and it would allow them to interact with the 6 000 000+ current Fediverse users.

**Comment by exentrich** [comment]
Feature requests are here https://raindropio.canny.io/

**Comment by RokeJulianLockhart** [comment]
> https://github.com/raindropio/app/issues/41#issuecomment-2561083439

@exentrich and @xplosionmind, reposted to https://raindropio.canny.io/feature-requests/p/integrate-activitypub-the-fediverse.
