### ISSUE TITLE
Атрибуты ICON_URI, ICON при экспорте

### ISSUE THREAD

**Issue by ffytczuthp** [raindropio/app#44]
При экспорте не добавляются допустимые атрибуты **ICON_URI**, **ICON** (можно посмотреть, как **Firefox**, **Chrome** экспортируют закладки), т.е. информация об иконке теряется. Это плохо. Можно ли поправить?
Учитываются ли эти атрибуты при импорте, не проверяла.
Спасибо.

**Comment by exentrich** [comment]
Данный атрибут содержит URL или Base64 фавиконки сайта. Никакой пользы в нем нет, все браузеры умеют автоматически загружать их
