### ISSUE TITLE
Ключевое слово для закладки

### ISSUE THREAD

**Issue by ffytczuthp** [raindropio/app#45]
В **Firefox** для закладки можно указать ключевое слово (для быстрого вызова через адресную строку) - атрибут **SHORTCUTURL**. Это иногда очень-очень удобно. Непосредственно в **Raindrop** это использовать нельзя, но хочется, чтобы ключевое слово для закладки сохранялось при экспорте/импорте, потому что экспортированный HTML-файл может импортироваться в **Firefox**. Пусть ключевое слово даже и не показывается в **Raindrop**, но всё равно хранится/экспортируется/импортируется.
Спасибо.

**Comment by exentrich** [comment]
Не планируется
