### ISSUE TITLE
Новые типы закладок - локальные файлы, букмарклеты, FTP

### ISSUE THREAD

**Issue by ffytczuthp** [raindropio/app#46]
1. Иногда HTML-страница находится на локальном диске, а не в Интернете. И иногда нужны закладки именно на такие HTML-файлы. Но сейчас такие закладки создать невозможно (также невозможны импорт/экспорт). Можно ли добавить это? 
_Пример_:  ```file:///C:/Documents/Administrator/Desktop/RopArcDocum-03-21.html```

2. Существуют такие закладки - букмарклеты - однострочный **JavaScript-код**. Исключительно полезная штука. Но сейчас такие закладки создать невозможно (также невозможны импорт/экспорт). Можно ли добавить это? 
_Пример_:  ```javascript:location.href='https://clck.ru/?url='+encodeURIComponent(location.href)```
Я не уверена, что из **Raindrop** можно будет такую закладку запустить, но было бы хорошо, чтобы её всё-таки можно было создать/импортировать/экспортировать, т.к. она может быть использована непосредственно в браузере (после экспортирования из **Raindrop**).

3. Бывают закладки на **FTP-сервера**. **FTP** до сих пор широко используется. Такие закладки нужны.
_Пример_:  ```ftp://ftp.byfly.by/ubuntu/```

Спасибо.

**Comment by exentrich** [comment]
1. Даже если добавить возможность создавать закладки на локальные файлы (`file://`) браузер их все-равно откажется открывать, это запрещено во всех современных браузерах https://security.stackexchange.com/questions/153706/why-local-links-are-disabled-by-default-in-modern-browsers

2. JS ссылки не безопасны
3. FTP ссылки поддерживаются
