### ISSUE TITLE
Полная дата и в нужном формате

### ISSUE THREAD

**Issue by ffytczuthp** [raindropio/app#49]
1. Если закладка создана в текущем году, то год не показывается. Зачем? Почему не показывать всегда год? Это нужно для единообразия.
2. Сделайте возможность выбора формата даты, пожалуйста. В разных странах форматы даты разные. **Raindrop** не учитывает это. А лучше показывать дату в международном, единообразном, стандартизированном формате **ISO 8601**: например, ```2022-03-22```. Это международный стандарт; его понимают все люди во всех странах, и понимают однозначно.

Спасибо

**Comment by exentrich** [comment]
> 1. Если закладка создана в текущем году, то год не показывается. Зачем? Почему не показывать всегда год? Это нужно для единообразия.

Вот, логика ведь очевидна :)

> 2. Сделайте возможность выбора формата даты, пожалуйста. В разных странах форматы даты разные. Raindrop не учитывает это. А лучше показывать дату в международном, единообразном, стандартизированном формате ISO 8601: например, 2022-03-22. Это международный стандарт; его понимают все люди во всех странах, и понимают однозначно.

Формат даты используется тот, что указан в системе
