### ISSUE TITLE
Public Collections Display Issues

### ISSUE THREAD

**Issue by denvergeeks** [raindropio/app#5]
![raindrop-collection-on-iphone-x](https://user-images.githubusercontent.com/322529/97229116-7da1eb80-179d-11eb-9457-9f1642047545.PNG)
Rustem -- I want to continue to use Raindrops Public Collections/Pages, but they are **_unusable_** until I can modify the app.css or otherwise modify the display to remove the sidebar.

Because of this, Public Collections are also unusable on any phone.

Please advise if there is a work-around or a way to **_control the display of Public Collections_**!

Thank You!!!

**Comment by denvergeeks** [comment]
Bump!

**Comment by denvergeeks** [comment]
Bummpety-Bump-Bump!

**Comment by denvergeeks** [comment]
I seriously need this to display correctly on mobile.

**Comment by ryota-murakami** [comment]
@denvergeeks hi, looks like you have a issue on mobile site but app author might really busy.
So I want to fix your issue if it I can after investigation.

I'll do an investigation in my spare time for about a week and submit comment about progress!

**Comment by denvergeeks** [comment]
Gee whiz, THANK YOU so much @ryota-murakami !!! I would be _**most happy**_ to _**pay you**_ for your time. Please PM or email me when you get a chance.

**Comment by ryota-murakami** [comment]
@denvergeeks Hi, I've planed try it at last weekend, however I couldn't make time job reason 😭
I'll try next weekend!

**Comment by denvergeeks** [comment]
Thank you so much for letting me know!!! 🤓  I'm glad you have paid job
work too!

Jen

Jen Wallace
💻 Denver Geeks
Tel: 303-647-1411
http://DenverGEEKS.com <http://denvergeeks.com/>

**Comment by denvergeeks** [comment]
WHAT DO MY EYES BEHOLD??? MY FIRST 2021 WISH CAME TRUE!!! THANK YOU THANK YOU THANK YOU FOR REMOVING THE BLASTED SIDEBAR!!!
