### ISSUE TITLE
Permanent copies of articles are missing all sort of details (images, etc.)

### ISSUE THREAD

**Issue by camflint** [raindropio/app#51]
The permanent copy feature of Raindrop.io is not working correctly at all. Here is a sample to illustrate the problem:

Original:
![sample-article-original-correct](https://user-images.githubusercontent.com/2079548/168447311-cb186acb-535b-4f6f-9eac-b2cdf619a685.png)

Permanent copy:
![sample-article-permanent-copy-incorrect](https://user-images.githubusercontent.com/2079548/168447318-ef9774c0-2415-4d0e-b4b2-938551bd7dbf.png)

The article source link: https://maggieappleton.com/programmatic-notes

**Comment by exentrich** [comment]
Permanent copy of this website is greatly improved. Please send a request to info@raindrop.io and I will reindex this website on your account
