### ISSUE TITLE
The extension shouldn't log out when browser data is cleared

### ISSUE THREAD

**Issue by github-account1111** [raindropio/app#52]
My browser is set to clear browsing data on exit.
Raindrop seems to store its extension login data in cookies, so every time I reopen the browser I have to log in all over.

That's quite annoying, extensions shouldn't do that.
They should use the local storage api provided by the browser to make sure things persist between sessions.
It's how Bitwarden, uBlock Origin, 1Password and other popular security- and privacy-focused extensions do it.

**Comment by exentrich** [comment]
Anything beside cookies are INSECURE

**Comment by RokeJulianLockhart** [comment]
> https://github.com/raindropio/app/issues/52#issuecomment-2561073279

@exentrich, that seems incredibly improbable, *if* Bitwarden acts as @github-account1111 states. Can you elaborate?
