### ISSUE TITLE
Funny thing happens when I try to save Youtube videos using ChromeExtension

### ISSUE THREAD

**Issue by takao-h** [raindropio/app#53]
When I try to save a Youtube video using ChromeExtension, the video thumbnail and title refer to the cache.

For example
https://www.youtube.com/watch?v=xxxxxx&ab_channel=YYY
After accessing
https://www.youtube.com/watch?v=zzzzz&ab_channel=YYY
the URL of the saved data is https://www.youtube.com/watch?v=zzzzz&ab_channel=YYY
but the thumbnails and titles are from https://www.youtube.com/watch?v=xxxxxx&ab_channel=YYY
is used for thumbnails and titles.

**Comment by exentrich** [comment]
Please provide actual URLs and steps to reproduce
