### ISSUE TITLE
Firefox / Windows 10: Categories Are Missing

### ISSUE THREAD

**Issue by gawlinski-com** [raindropio/app#55]
Noticed an issue where the bookmark categories / folders are missing.

Removing the plugin & reinstalling will provide a temporary solution for a month or two.  But shortly later, the folders will be missing again.

Attached a screenshot.
![raindrop](https://user-images.githubusercontent.com/98241631/178599182-bcdef0d7-93c6-4bd0-a388-fa93ab9a589d.jpg)
  Before I re-install, let me know if I can send over logs or provide any information that would help with troubleshooting.  Appreciate the help and plugin, thank you!

**Comment by exentrich** [comment]
Please logout and login back, this should fix the problem
