### ISSUE TITLE
iOS App: keyboard covers the URL field

### ISSUE THREAD

**Issue by crazyyzarc** [raindropio/app#57]
I can't see the url, when the bookmark has a long description

https://user-images.githubusercontent.com/4954535/183353788-8b241200-68d1-4fc4-802c-04d70bc57cbe.mp4

**Comment by exentrich** [comment]
Scroll down doesn’t work?

**Comment by crazyyzarc** [comment]
Yes, except when I add a new bookmark in Raindrop, I can't scroll down without hiding the keyboard.
