### ISSUE TITLE
[browser-ext] Toolbar icon should change color when the page is already bookmarked

### ISSUE THREAD

**Issue by gerardbosch** [raindropio/app#59]
_Congrats! :tada:  Very handy application, I love that it is vendor-agnostic so I can access and store bookmarks independent of the browser I'm running. The search and previews are also great!_

---

When the current page is already bookmarked, the toolbar button/icon 

![image](https://user-images.githubusercontent.com/30733556/197364902-ab4988f1-dce0-47b6-a4cc-b63110b14e14.png)

should indicate that fact (the same way native web browser bookmark star button does), by displaying another color. So the user have instant feedback about the page.

This feature is 100% equivalent to the following one also requested in Pocket years ago, and not implemented at the time of writing:
https://bugzilla.mozilla.org/show_bug.cgi?id=1402155

Right now when you click on the button, you can see any of these, depending whether the page is already saved or not:

![image](https://user-images.githubusercontent.com/30733556/197365330-3c9198f6-28fb-403f-a996-01368990af94.png)
![image](https://user-images.githubusercontent.com/30733556/197365332-4d0ef935-5f1d-4f8e-bbc3-8abce134f169.png)

Again, thanks for this very cool project! ^_^ Cheers!

**Comment by gerardbosch** [comment]
Actually I see this icon in the `assets` directory: https://github.com/raindropio/app/blob/5424677c308d004220fc078de71bff65d2118251/src/assets/icons/cloud_active.svg

But in my case I never see the cloud filled.
I'm on Brave v1.44.112 (Oct 12th, 2022) Chromium to 106.0.5249.119 (64-bit).

Thanks

**Comment by exentrich** [comment]
Hello!
You need to give additional permission to enable saved page indicator:
https://help.raindrop.io/browser-extension#saved-indicator

**Comment by gerardbosch** [comment]
Thanks for your prompt reply @exentrich. Now I realize I was missing to grant the permission to the extension, and that the perm is also required to store all tabs, enable highlight (and maybe other additional features?).

![image](https://user-images.githubusercontent.com/30733556/197401830-04b0cfda-9aaa-4bec-817b-27f3746716c5.png)

But this just brought me a new question:

- Should I grant such strong _"Read and change all your data on the websites you visit"_ permission to show the indicator status? I mean, is that perm really required for that feature? I appreciate the Principle of Least Permission, so I questioned myself if that's strictly necessary. For example, to store all tabs, other extensions can do it with reduced permission like _"Read your browsing history"_ e.g. OneTab extension.

I'm not confortable giving extensions access to all browser data, and would prefer to give the minimal necessary to make it work.

Would that be possible? What do you think?
Cheers!
