### ISSUE TITLE
[Feature Request] Make bookmarks as suggested search across browsers

### ISSUE THREAD

**Issue by tripathyprateek** [raindropio/app#6]
@exentrich it would be really be a helpful feature if there was a way when I search something, my bookmarks saved in raindrop Chrome extension come up as suggested searches.

**Comment by KlausDevWalker** [comment]
This already happens when you add Raindrop as a search engine. In my case I type "rd"+ space and the search is made through my Raindrop items.

**Comment by tripathyprateek** [comment]
@KlausDevWalker thanks a lot for this tip. "rd"+tab works for me.
