### ISSUE TITLE
Hashref in URL can makes Raindrop innactive

### ISSUE THREAD

**Issue by ramification** [raindropio/app#61]
# Example

I'm highlighting some text in the react hooks ref page... but I start doing this when there's a hash in the URL (#usememo for example).

then, a few days later, I'm opening the page but all of the highlights are lost because the displayed URL hasn't the hash, or just because i've clicked on an internal anchor link (like #useEffect)

# Conclusion

I have to remove manually every hash in urls of all my saved pages on raindrop... that's not cool at all !

**Comment by exentrich** [comment]
Will be fixed in Chrome extension 5.6.66
All other browsers will receive an update next week
