### ISSUE TITLE
[Feature Request] Change the icon to include a checkmark on a bookmarked page

### ISSUE THREAD

**Issue by piavgh** [raindropio/app#75]
Hi everyone,

At the moment, when visiting a bookmarked page with Raindrop, I have to click on the "cloud icon" of Raindrop and look for the `Saved` button to know if this page was bookmarked before.

It will be better if when visiting this page, the `cloud icon` turns into something else (such as with a checkmark, with the sunshine, or just different color) so that we know immediately that the page was bookmarked before.

Is this a good idea?

**Comment by Tback1** [comment]
it could
![image](https://user-images.githubusercontent.com/8872546/235755813-3c0fc6e1-7c25-49a3-b7b1-d110e43986b5.png)
like this .

just need to open the miniapp ,in the setting to ask rights to visit the web date right for every site

**Comment by piavgh** [comment]
> it could ![image](https://user-images.githubusercontent.com/8872546/235755813-3c0fc6e1-7c25-49a3-b7b1-d110e43986b5.png) like this .
> 
> just need to open the miniapp ,in the setting to ask rights to visit the web date right for every site ![image](https://user-images.githubusercontent.com/8872546/235758117-c92a2441-8a4c-4e47-a215-ef4daf8a2f8f.png) ![image](https://user-images.githubusercontent.com/8872546/235758569-ca02ea07-769f-4162-9c93-e9bd2bc2fddc.png)
> 
> I don't know why it not ask after the initial instelled, and if you forgot to give the right ,it hide very deep to set it. Even in the Chrome setting it could not open，must in the miniapp to ask

Thanks a lot, I didn't realize that this feature exists
