### ISSUE TITLE
Extension does not work in Firefox with third party cookies disabled

### ISSUE THREAD

**Issue by h-five-e** [raindropio/app#78]
To login the extension wants to read cookies from https://api.raindrop.io/v1/raindrops/links but can't because third party cookies are disabled. I get this log in the extension debugger:

> Request to access cookie or storage on “https://api.raindrop.io/v1/raindrops/links” was blocked because we are blocking all third-party storage access requests and content blocking is enabled.

When enabling third party cookies, the extension works and is logged in, but only until I disable 3rd party cookies again. I would appreciate a fallback where the extension uses it's own storage to store a session cookie when it can't access the one on the website.

**Comment by exentrich** [comment]
Any method of storing an authentication token other than Cookies is insecure
https://levelup.gitconnected.com/why-cookie-is-preferable-compared-to-localstorage-when-it-comes-to-authentication-b43ac5610be6
