### ISSUE TITLE
Suggestion: Drag & Drop to assign tags

### ISSUE THREAD

**Issue by jo-me** [raindropio/app#8]
It is currently possible to move something between collections by drag & drop to the desired collection.
For tagging, you have to go to the edit  screen and type or select the tags from the dropdown menu. 

A quicker way to assign tags could be to drag & drop on the tags displayed in the sidebar without going through the edit screen.
It would feel quicker and more elegant than going to the edit page.

**Comment by exentrich** [comment]
Thanks! Great idea

**Comment by exentrich** [comment]
https://raindropio.canny.io/feature-requests/p/add-tags-via-drag-drop
