### ISSUE TITLE
Spelling Mistake

### ISSUE THREAD

**Issue by SpoofingMyName** [raindropio/app#80]
Minor one, "styling" spelled wrong when hovering over markdown icon.

![image](https://github.com/raindropio/app/assets/72457367/8084ea80-d368-46a0-9e40-de088d88c6ae)

**Comment by ai-naymul** [comment]
Hey I would love to work on that, may I?

**Comment by SpoofingMyName** [comment]
> 

A pull request has already fixed the issue and is waiting for approval

**Comment by SpoofingMyName** [comment]
Pull request submitted by someone
