### ISSUE TITLE
[Feature Request] Task support (CalDAV?)

### ISSUE THREAD

**Issue by RokeJulianLockhart** [raindropio/app#82]
I currently use https://app.raindrop.io for my wishlist. However, it's not ideal, I have no way of marking a task as complete or incomplete except with tags. This doesn't provide an adequate visual cue or organization, since I can't set permanent per-(folder/tag) [sorting](https://github.com/raindropio/app/issues/84#issue-1773260658) and [filtering](https://github.com/raindropio/app/issues/83#issue-1773259863).

https://github.com/wishlephant/wishlephant-website/issues/1 is the ideal solution.

<details>

Relevant:

0.  [ ] https://gitlab.com/gitlab-org/gitlab/-/issues/14390
0.  [ ] https://github.com/kaleidos-ventures/taiga-back/issues/128#issue-1688815129
0.  [ ] https://github.com/wishlephant/wishlephant-website/issues/1#issue-1782844817
0.  [ ] https://github.com/bookwyrm-social/bookwyrm/issues/2952#issue-1847099016
0.  [ ] https://github.com/recloudstream/cloudstream/issues/550#issue-1847127445
0.  [ ] https://github.com/LagradOst/QuickNovel/issues/184#issue-1847122964
0.	[ ] https://github.com/ValveSoftware/steam-for-linux/issues/10019#issue-1868495803

**Comment by exentrich** [comment]
https://better.raindrop.io/

**Comment by RokeJulianLockhart** [comment]
> https://github.com/raindropio/app/issues/82#issuecomment-2061554429

@exentrich, transferred to https://raindropio.canny.io/feature-requests/p/task-support-caldav, per https://github.com/raindropio/app/issues/112#issuecomment-2061528222.
