### ISSUE TITLE
[Feature Request] Filter support.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [raindropio/app#83]
When viewing a certain folder or tag, I can't choose to exclude and/or include certain tags or types (directory vs entry).

**Comment by exentrich** [comment]
https://better.raindrop.io/

**Comment by RokeJulianLockhart** [comment]
> https://github.com/raindropio/app/issues/83#issuecomment-2061553589

@exentrich, transferred to https://raindropio.canny.io/feature-requests/p/filter-support, per https://github.com/raindropio/app/issues/112#issuecomment-2061528222.
