### ISSUE TITLE
Click extension to open raindrop

### ISSUE THREAD

**Issue by d3ltr0n** [raindropio/app#89]
I'd love a way of getting into raindrop or via a click on the extension.  

I find I am always accidentally clicking the extension to open rainrop and creating a bookmark by mistake. It'd be great if there was a right click or key combo to open raindrop in a new tab.

**Comment by exentrich** [comment]
<img width="392" alt="Screenshot 2023-07-13 at 10 49 43" src="https://github.com/raindropio/app/assets/1203812/a74c0ab1-bca0-41dc-9c3a-17a067b271f4">
Yes you can right click on a extension and click Raindrop.io to open it in new tab.
There also a shortcut https://help.raindrop.io/browser-extension
