### ISSUE TITLE
Save button hidden by tags dropdown

### ISSUE THREAD

**Issue by pbinkley** [raindropio/app#91]
I love everything about the browser extension except this, where the save button is hidden behind the dropdown of tags. When I'm finished adding tags I have to click somewhere else, being careful not to click somewhere that does something, before I can click save. It would be better if the save button were always accessible. (This is in Firefox on Ubuntu)

![Screenshot from 2023-07-10 13-43-33](https://github.com/raindropio/app/assets/272816/37a31f70-d4cf-4707-8f35-0c7feed5a4a3)

**Comment by exentrich** [comment]
Hello! Just press Enter to save.
Visibility of saved button will be improved in future updates, thanks

**Comment by pbinkley** [comment]
Thanks! I'm glad it's in the plans.
