### ISSUE TITLE
[Feature Request] Add “amount” attribute.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [raindropio/app#92]
https://raindropio.canny.io/feature-requests/p/add-amount-attribute

> Necessary for wishlists. I want to migrate from Amazon Wishlists to this, but can't until importance and amount are added.

**Comment by rokejulianlockhart** [comment]
https://github.com/raindropio/app/issues/93#issue-1806247878

**Comment by RokeJulianLockhart** [comment]
> https://github.com/raindropio/app/issues/92#event-12510077746

@exentrich, transferred to https://raindropio.canny.io/feature-requests/p/add-amount-attribute-1, per https://github.com/raindropio/app/issues/112#issuecomment-2061528222.
