### ISSUE TITLE
Background for images

### ISSUE THREAD

**Issue by kud** [raindropio/app#95]
Hey,

It could be great to have a background like black or grey behind image preview in moodboard or cards board.

<img width="374" alt="screenshot-2023-08-26-13-14-44@2x" src="https://github.com/raindropio/app/assets/655838/5b6c077a-790c-4b45-9df7-fff720f260bc">

**Comment by LorenAmelang** [comment]
I think those white-background images are just what was on the linked page. Almost all of mine are similar, unless the original page was in dark mode. But they are a bit blindingly bright compared to the text - could there be an option to reduce the brightness of images? Or increase the contrast of the Raindrop added text?

**Comment by kud** [comment]
Not sure it's still an issue for now.
