### ISSUE TITLE
[Feature Request] Metadata options depending only on the current collection

### ISSUE THREAD

**Issue by kud** [raindropio/app#96]
Hey,

When changing the types of metadata displayed, it remains consistent across all similar views. For example, if you select "cards" for two collections, changing the available metadata will apply to all collections, instead of just the current one.

It would be beneficial to have the option to choose the metadata available exclusively for the current collection.

<img width="187" alt="screenshot-2023-08-26-19-43-07@2x" src="https://github.com/raindropio/app/assets/655838/373cafa9-b075-4383-8423-1b2199242cc3">

**Comment by exentrich** [comment]
Please add feature requests here https://better.raindrop.io/
