### ISSUE TITLE
[Feature Request] SMB-Share (CIFS) redirect to Windows-Explorer

### ISSUE THREAD

**Issue by Titanfinger** [raindropio/app#97]
Dear Developer

Much appreciated this awsome piece of Software!

Unfortunately i couldnt open a Link to my SMB-Share.
For my work as a Sysadmin a have to remember not only Web-Links but also SMB-Folder path to Software Storage and a lot of diffrent path to local and Network-shares like FTP, SFTP, SAMBA etc.

The dream would be an integrated File-manager, but i belive thats to much work.

So my request is to simple open my Windows-Explorer when i click on a SMB-Share instead of the Web-Browser.
That would be awsome!

**Comment by exentrich** [comment]
Please add feature requests here https://better.raindrop.io/
